version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"   # EC2 will expose port 3306 if needed
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    container_name: ecommerce-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    container_name: ecommerce-frontend
    restart: always
    environment:
      REACT_APP_API_URL: http://51.20.192.180:8081  # <-- EC2 IP for backend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge

